import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-icons-showcase',
  templateUrl: './icons-showcase.component.html',
  styleUrls: ['./icons-showcase.component.scss'],
})
export class IconsShowcaseComponent implements OnInit {
  icons = [
    'add-account.svg',
    'add-capsule-blue.svg',
    'add-capsule-grey.svg',
    'add-white.svg',
    'amend.svg',
    'calendar.svg',
    'caret.svg',
    'check.svg',
    'clip.svg',
    'close-20px.svg',
    'close-blue.svg',
    'close-grey.svg',
    'close-white.svg',
    'close_blue_active.svg',
    'close_grey_active.svg',
    'close_white_active.svg',
    'download.svg',
    'download-empty.svg',
    'download-retry.svg',
    'download-success.svg',
    'edit.svg',
    'error.svg',
    'expand.svg',
    'expand-selected.svg',
    'help.svg',
    'invalid.png',
    'inbox_iras.svg',
    'inbox_user.svg',
    'info.svg',
    'minimise.svg',
    'minus.svg',
    'notification-masthead.svg',
    'login.svg',
    'pay-taxes.svg',
    'password.svg',
    'png-attention.svg',
    'ribbon.svg',
    'save-pdf.svg',
    'save-draft2.svg',
    'search.svg',
    'sortdown.svg',
    'sortup.svg',
    'sortupdown.svg',
    'sort-up-down-blue.svg',
    'stepper-add.svg',
    'stepper-minus.svg',
    'svg-undo.svg',
    'success.svg',
    'trash-bin-grey.svg',
    'trash-bin.svg',
    'leasetenancy.svg',
    'payment-plan.svg',
    'switch.svg',
    'location.svg',
    'print.svg',
    'tax-bill.svg',
    'copy.svg',
    'location-grey.svg',
    'qr-code.svg',
    'unp.svg',
    'export.svg',
    'markallasread-active.svg',
    'refund.svg',
    'update-contact.svg',
    'giro.svg',
    'markallasread-grey.svg',
    'request-extension.svg',
    'view.svg',
    'giro-black.svg',
    'mortgage.svg',
    'saleandpurchase.svg',
    'view-acc-summary.svg',
    'giro-grey.svg',
    'mtm.svg',
    'savedraft.svg',
    'view-notices.svg',
    'hyperlink.svg',
    'pay.svg',
    'sharetransfer.svg',
    'warning.svg',
  ];

  constructor() {}

  ngOnInit() {}
}
